networks:
  backend:
    driver: bridge

volumes:
  redis_data:
    driver: local

services:
  redis:
    image: redis:alpine
    networks:
      - backend
    volumes:
      - redis_data:/data


  telegram_bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./src:/app/src
    networks:
      - backend
    command: uv run python -m src.cmd.main
